services:
    dittobot:
        build:
            context: .
            target: production
        user: "1000:1000"
        restart: unless-stopped
        ports:
            - "3030:3000"
        env_file:
            - .env
        volumes:
            # local provider only
            # - ./data:/app/data
            - ./private-key.pem:/app/private-key.pem:ro
        tmpfs:
            - /tmp
        read_only: true
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
